package com.qhit.lh.g4.perfact.exam.subject_management.bean;

import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.g4.perfact.exam.questions_management.bean.MachineTest;
import com.qhit.lh.g4.perfact.exam.questions_management.bean.WrittenTest;

// Generated 2018-1-1 21:40:45 by Hibernate Tools 4.3.1

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int csId;
	private String csName;
	private String stage;
	private String major;
	
	private Set<WrittenTest> writtenTests = new HashSet<>();
	private Set<MachineTest> machineTests = new HashSet<>();

	public Course() {
	}

	public Course(int csId, String csName, String stage) {
		this.csId = csId;
		this.csName = csName;
		this.stage = stage;
	}

	public int getCsId() {
		return this.csId;
	}

	public void setCsId(int csId) {
		this.csId = csId;
	}

	public String getCsName() {
		return this.csName;
	}

	public void setCsName(String csName) {
		this.csName = csName;
	}

	public String getStage() {
		return this.stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	public String getMajor() {
		return major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Set<WrittenTest> getWrittenTests() {
		return writtenTests;
	}

	public void setWrittenTests(Set<WrittenTest> writtenTests) {
		this.writtenTests = writtenTests;
	}

	public Set<MachineTest> getMachineTests() {
		return machineTests;
	}

	public void setMachineTests(Set<MachineTest> machineTests) {
		this.machineTests = machineTests;
	}

}
