package com.qhit.lh.g4.perfact.exam.questions_management.bean;

import com.qhit.lh.g4.perfact.exam.subject_management.bean.Course;

// Generated 2018-1-1 21:40:45 by Hibernate Tools 4.3.1

/**
 * Question generated by hbm2java
 */
public class MachineTest implements java.io.Serializable {
	private Integer qid;
	private String qtitle;
	private String degree;
	private Integer csId;
	private String chapter;

	//n-1
	private Course course;

	// Constructors

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	/** default constructor */
	public MachineTest() {
	}



	public MachineTest(Integer qid, String qtitle, String degree, Integer csId,
			String chapter) {
		super();
		this.qid = qid;
		this.qtitle = qtitle;
		this.degree = degree;
		this.csId = csId;
		this.chapter = chapter;
	}

	/** minimal constructor */

	// Property accessors

	public Integer getCsId() {
		return csId;
	}

	public void setCsId(Integer csId) {
		this.csId = csId;
	}
	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public String getQtitle() {
		return this.qtitle;
	}

	public void setQtitle(String qtitle) {
		this.qtitle = qtitle;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}
}
