package com.qhit.lh.g4.perfact.exam.common.bean;
// Generated 2017-12-28 17:48:06 by Hibernate Tools 4.3.1

import com.qhit.lh.g4.perfact.exam.student_management.bean.Student;
import com.qhit.lh.g4.perfact.exam.teacher_management.bean.Teacher;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String name;
	private String pwd;
	private int role;

	private Student student;
	private Teacher teachaer;
	
	public Users() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Users(String name, String pwd, int role, Teacher teachaer, Student student) {
		super();
		this.name = name;
		this.pwd = pwd;
		this.role = role;
		this.teachaer = teachaer;
		this.student = student;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPwd() {
		return pwd;
	}
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	public int getRole() {
		return role;
	}
	public void setRole(int role) {
		this.role = role;
	}
	public Teacher getTeachaer() {
		return teachaer;
	}
	public void setTeachaer(Teacher teachaer) {
		this.teachaer = teachaer;
	}
	public Student getStudent() {
		return student;
	}
	public void setStudent(Student student) {
		this.student = student;
	}
	
	

}
